#docker-compose -f "compose-docker.yml" down
#docker-compose -f "compose-docker.yml" up -d
version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer_docker
    privileged: true
    ports:
      - "9000:9000"
    volumes:
      - "./data/portainer_data_docker:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - TZ=America/Bogota  # Ejemplo de variable de entorno
    networks:
      - portainer_network  # Ejemplo de red personalizada
    restart: always
networks:
  portainer_network:  # Definición de la red
    driver: bridge

